### ISSUE TITLE
Possible Size Limit

### ISSUE THREAD

**Issue by neur1n** [cpetry/NormalMap-Online#16]
Hello Christian. I was trying to upload an 8192x8192 image to produce map, but I could only get the bottom left corner part. After I resized the original image to 4096x4096, everything works fine. I don't know if it is an known issue/limitation. And thanks for your great work.

**Comment by TheTyrius** [comment]
Same here. I will try resizing for now, but I'd be great to support high resolutions in the future :)

**Comment by cpetry** [comment]
I think this depends on your hardware specs. My desktop PC handles 8k without a problem (though it takes a while).
Firefox, NVIDIA Geforce GTX 1060
