### ISSUE TITLE
Seems to be completely broken

### ISSUE THREAD

**Issue by thevbw** [cpetry/NormalMap-Online#23]
Am I missing something? No part of the app works except loading in textures

**Comment by Calinou** [comment]
It works here on Firefox 83 on Fedora 33.

**Comment by Antidote00** [comment]
Works fine on Windows 10 Chrome 87, Firefox 83 and Edge.

Could you please provide some more information. What Browser, what OS and especially the image file you used. Otherwise no one is able to help you out.

**Comment by cpetry** [comment]
I can confirm that it works on Windows 10 Firefox 83 64Bit.
@speccius please specify!

By the way, thanks @Calinou and @Antidote00 :)

**Comment by thevbw** [comment]
Using windows 7 64 bit and chrome 86. Worked a while ago but now nothing. The right and centre boxes on the page are empty and none of the buttons or sliders do anything except loading images in. Tried the default image and various PNG files.

**Comment by Calinou** [comment]
@speccius Try opening the browser console (<kbd>F12</kbd> or <kbd>Ctrl + Shift + I</kbd>) then reloading the page. If you get any error messages, can you copy them here?

**Comment by thevbw** [comment]
I remember there were tons of errors, one sec

**Comment by thevbw** [comment]
Some messages have been moved to the Issues panel.
View issues
(index):44 Mixed Content: The page at 'https://cpetry.github.io/NormalMap-Online/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:700'. This request has been blocked; the content must be served over HTTPS.
three.min.js:149 THREE.WebGLRenderer 80
three.min.js:153 THREE.WebGLRenderer: Error creating WebGL context.
three.min.js:112 Uncaught TypeError: Cannot read property 'getExtension' of null
    at Object.get (three.min.js:112)
    at new rd (three.min.js:153)
    at new <anonymous> (renderView.js:28)
    at renderView.js:25
main.js:28 Uncaught TypeError: Cannot read property 'initRenderer' of undefined
    at main.js:28
three.min.js:149 THREE.WebGLRenderer 80
three.min.js:153 THREE.WebGLRenderer: Error creating WebGL context.
three.min.js:112 Uncaught TypeError: Cannot read property 'getExtension' of null
    at Object.get (three.min.js:112)
    at new rd (three.min.js:153)
    at Object.renderNormalview_init (renderNormalview.js:50)
    at Image.height_image.onload (filedrop.js:208)
filedrop.js:319 Uncaught TypeError: Cannot set property 'needsUpdate' of undefined
    at Image.picture_above.onload (filedrop.js:319)
filedrop.js:341 Uncaught TypeError: Cannot set property 'needsUpdate' of undefined
    at Image.picture_right.onload (filedrop.js:341)
filedrop.js:352 Uncaught TypeError: Cannot set property 'needsUpdate' of undefined
    at Image.picture_below.onload (filedrop.js:352)
filedrop.js:330 Uncaught TypeError: Cannot set property 'needsUpdate' of undefined
    at Image.picture_left.onload (filedrop.js:330)
7
normalMap.js:108 Uncaught TypeError: Cannot read property 'dz' of undefined
    at Object.setNormalSetting (normalMap.js:108)
    at HTMLInputElement.oninput ((index):303)
normalMap.js:108 Uncaught TypeError: Cannot read property 'dz' of undefined
    at Object.setNormalSetting (normalMap.js:108)
    at HTMLInputElement.onchange ((index):303)
normalMap.js:108 Uncaught TypeError: Cannot read property 'dz' of undefined
    at Object.setNormalSetting (normalMap.js:108)
    at HTMLInputElement.oninput ((index):303)
normalMap.js:108 Uncaught TypeError: Cannot read property 'dz' of undefined
    at Object.setNormalSetting (normalMap.js:108)
    at HTMLInputElement.onchange ((index):303)
4
normalMap.js:108 Uncaught TypeError: Cannot read property 'dz' of undefined
    at Object.setNormalSetting (normalMap.js:108)
    at HTMLInputElement.oninput ((index):303)
normalMap.js:108 Uncaught TypeError: Cannot read property 'dz' of undefined
    at Object.setNormalSetting (normalMap.js:108)
    at HTMLInputElement.onchange ((index):303)
(index):1 Mixed Content: The page at 'https://cpetry.github.io/NormalMap-Online/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:700'. This request has been blocked; the content must be served over HTTPS.
﻿
​copied from the console, even more errors appear when i try to do things in the app

**Comment by thevbw** [comment]
Updated chrome and issue resolved. Possible RAM clogging issue.
(Great webapp by the way!)
