### ISSUE TITLE
The recent changes you've made caused this to stop working on my machine...

### ISSUE THREAD

**Issue by ghost** [cpetry/NormalMap-Online#27]
![image](https://user-images.githubusercontent.com/60198160/192047324-7b063c91-9e6e-4a87-949c-babd52e06e88.png)
![image](https://user-images.githubusercontent.com/60198160/192047376-51128df7-8090-43ef-9693-ada49443f03c.png)
![image](https://user-images.githubusercontent.com/60198160/192047407-494b8701-e36d-4f60-b766-e1eca09cf8db.png)

**Comment by ghost** [comment]
The issue seems to be in https://github.com/cpetry/NormalMap-Online/blob/gh-pages/javascripts/shader/HorizontalBlurShader.js on line 76 where you forgot to delete the leading `",` when you changed the JSON.

**Comment by cpetry** [comment]
Closed by your PR. Thanks again!
