### ISSUE TITLE
Specular, AO and Displacement are not working

### ISSUE THREAD

**Issue by psdwizzard** [cpetry/NormalMap-Online#30]
They don't seem to preview when I open the index site. When I download them and open them, they are just empty pngs at 300x150. I have restarted just to make sure it's not on me. I have also tried it on another computer as well with the same results.

**Comment by psdwizzard** [comment]
![image](https://github.com/cpetry/NormalMap-Online/assets/22041607/fd1b9f4c-d41c-4c2c-9dda-6b7d7b0b2509)

**Comment by cpetry** [comment]
Well that's an easy issue:

You are trying to use normal map online on your local PC without a server. This does not work. I think this is due to accessing files that are located relatively on the webpage. Not sure anymore about the details.

Just create a local http Python server or try something from within vscode to test. Otherwise just use the online version on GitHub pages

**Comment by cpetry** [comment]
This is the URL:
https://cpetry.github.io/NormalMap-Online/

**Comment by psdwizzard** [comment]
Ill give the local http Python server a try. I have a big batch of these to do and I was getting odd errors last night on the web-based version and did not want hog public resources.

**Comment by cpetry** [comment]
This page is running completely on your machine only. The browser just fetches the files (images, JavaScript, shaders) and your PC itself runs the application.
No problem there.

**Comment by cpetry** [comment]
In case you have security concerns of your files I can assure you that my code does not try to steal or send anything anywhere. What's yours is yours and also the created content stays yours.
Assumed that you have usage rights 😉

**Comment by psdwizzard** [comment]
I got it running at home with a python server. it was not a security issues I just had 100s of these and I did not want to clog a system for everyone or get kick. Now I just need to see if I can get batch working. it just keeps giving me the same set over and over.
