### ISSUE TITLE
Thinking about improvements

### ISSUE THREAD

**Issue by cpetry** [cpetry/NormalMap-Online#4]
Spec,AO, Disp... -maps

**Comment by seanmavley** [comment]
Can I run instance of this on my local machine? if so, any pointers? Thanks

**Comment by cpetry** [comment]
Hello!

Well it does already run on your local machine.
The one and only thing the server does is to give you all the complete 
code and scripts your machine needs while loading the page.
Not a single map/texture gets saved or anything (github has no 
possibility of a database for that).

If you still want to run it on your pc (which completely doesn't make 
sense) you could use a python server.
That's how I fix bugs or implement new features.
Though if you run it locally you won't get any improvements/changes i make.

Christian Petry
(www.petry-christian.de)

Am 14.01.2015 um 19:06 schrieb Nkansah Rexford:
